### ISSUE TITLE
improvment - add a healthcheck

### ISSUE THREAD

**Issue by bugaenkoleonid** [zocker-160/sheepit-docker-nvidia#4]
im using your new docker tag for deployment on vast.ai. Thank you so much for that, it works pretty well!

but sometimes agents hang up and  freeze the entire render queue 

Maybe you can use [this](https://hub.docker.com/r/mydigitalwalk/sheepit-docker?fbclid=IwAR0D6tO4w8pTmIQLEHUlBbQvSkEdecIdBDP-oJaVEFsbtQphlyFNb36mlQ8#:~:text=cache%0A%0Avolumes%3A%0A%20%20cache%3A-,Healthcheck,-A%20health%20check) solution in your image?

**Comment by zocker-160** [comment]
Sound like a good addition, I will look into it.

However it might also be useful to investigate why / where / when it is freezing, because normally this should be fixed in the sheepit client itself. 
I do not know if the sheepit client has a health check also, but I would argue that it would be its job to detect a stall and do something about it.

**Comment by DaCoolX** [comment]
If I recall correctly, that image does its healthcheck by watching the logs and maybe comparing timestamps.

Thing is, on older, community-driven Sheepit docker images, this tended to happen, I know because I run one constantly myself.

On the [official image](https://hub.docker.com/r/sheepitrenderfarm/client#!) this does not happen anymore.

Should also work with modern docker CUDA support, if it's needed.

Anywho, a native healthcheck in the client would probably be wise to implement. Just watching logs seems primitive and error-prone.

**Comment by zocker-160** [comment]
It is a client issue, had this happen natively too when running for a long time, not sure why you think this would be docker related, because it isn't.

A health check makes perfect sense in an environment where you pay per minute, so it is a very reasonable request.

**Comment by DaCoolX** [comment]
Just a hunch, used to happen every few months but it does not anymore.

I will see to it to get a health signal natively implemented in the client.

**Comment by bugaenkoleonid** [comment]
I couldn't run the official image on vast.ai

**Comment by DaCoolX** [comment]
I don't wanna clutter this issue with conversation of a separate docker image.
If you want, [our GitLab Issue Tracker](https://gitlab.com/sheepitrenderfarm/client-docker/-/issues)
You can also reach out to me on Discord via `@dacool`
